version: '3'

services:

  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway-ms
      dockerfile: dockerfile.prod
    image: us-west2-docker.pkg.dev/microservices-425700/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: us-west2-docker.pkg.dev/microservices-425700/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}      
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: us-west2-docker.pkg.dev/microservices-425700/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}      
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: us-west2-docker.pkg.dev/microservices-425700/image-registry/orders-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}      
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payment-ms:
    build:
      context: ./payment-ms
      dockerfile: dockerfile.prod
    image: us-west2-docker.pkg.dev/microservices-425700/image-registry/payment-ms
    ports:
      - ${PAYMENT_PORT}:${PAYMENT_PORT}
    environment:
      - PORT=${PAYMENT_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${PAYMENT_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENT_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_UR=${PAYMENT_STRIPE_CANCEL_UR}
      - STRIPE_ENDPOINT_SECRET=${PAYMENT_STRIPE_ENDPOINT_SECRET}  